version: '3.4'

services:

  authenticationdb:
    image: mysql

  sessioncache:
    image: redis:alpine
  
  texastaco.api.gateway:
    image: ${DOCKER_REGISTRY-}texastacoapigateway
    build:
      context: .
      dockerfile: src/Gateway/TexasTaco.Api.Gateway/Dockerfile

  texastaco.authentication.api:
    image: ${DOCKER_REGISTRY-}texastacoauthenticationapi
    build:
      context: .
      dockerfile: src/Authentication/TexasTaco.Authentication.Api/Dockerfile

volumes:
   authentication_db_volume:


