version: '3.4'

services:
  usersdb:
    image: mysql
    container_name: usersdb
    volumes:
      - usersdb_data:/var/lib/mysql

  texastaco.users:
    image: ${DOCKER_REGISTRY-}texastacousers
    build:
      context: .
      dockerfile: src/Services/TexasTaco.Users/Dockerfile

  texastaco.authorization:
    image: ${DOCKER_REGISTRY-}texastacoauthorization
    build:
      context: .
      dockerfile: src/Services/TexasTaco.Authorization/Dockerfile

volumes:
  usersdb_data:

