version: '3.4'

services:

  usersdb:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234 
      MYSQL_USER: mkopacz
      MYSQL_PASSWORD: mkopacz1234

  texastaco.users:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

