version: '3.4'

services:

  usersdb:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234 

  texastaco.users:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

