version: '3.4'

services:

  authenticationdb:
    image: mysql

  sessioncache:
    image: redis:alpine
  
  texastaco.api.gateway:
    image: ${DOCKER_REGISTRY-}texastacoapigateway
    build:
      context: .
      dockerfile: src/Gateway/TexasTaco.Api.Gateway/Dockerfile

  texastaco.authentication.api:
    image: ${DOCKER_REGISTRY-}texastacoauthenticationapi
    build:
      context: .
      dockerfile: src/Authentication/TexasTaco.Authentication.Api/Dockerfile
    depends_on:
      - authenticationdb
      - sessioncache
      - texastaco-mq

  texastaco-mq:
    image: rabbitmq:3-management
    container_name: texastaco-mq

  texastaco.users.api:
    image: ${DOCKER_REGISTRY-}texastacousersapi
    build:
      context: .
      dockerfile: src/Users/TexasTaco.Users.Api/Dockerfile
    depends_on:
      - texastaco-mq

volumes:
   authentication_db_volume:



