version: '3.4'

services:

  authenticationdb:
    container_name: authenticationdb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=authentication
    ports:
      - 3306:3306
    volumes:
      - authentication_db_volume:/var/lib/mysql

  texastaco.authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - AuthenticationDatabase:ConnectionString=server=authenticationdb;user=root;password=root1234;database=authentication;
    ports:
      - 5001:8080
    restart: always

