version: '3.4'

services:

  texastaco.authentication.api:
    container_name: texastaco.authentication.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - AuthenticationDatabase__ConnectionString=server=authentication-db;user=root;password=root1234;database=authentication;
      - CacheSettings__ConnectionString=authentication-cache:6379
      - SmtpOptions__SourceAddress=texastaco.notifications@gmail.com
      - SmtpOptions__Host=smtp.gmail.com
      - SmtpOptions__Password=hsfg wdxi ryhw qvee
      - SmtpOptions__Port=587
      - SmtpOptions__UseSsl=false
      - MessageBroker__Host=amqp://texastaco-queue:5672
      - MessageBroker__Username=admin
      - MessageBroker__Password=1234
      - DataProtectionSettings__CacheUri=authentication-cache
    ports:
      - 5001:8080
    restart: always

  texastaco.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5000:8080"

  texastaco.users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - UsersDatabase__ConnectionString=server=users-db;user=root;password=root1234;database=users;
      - MessageBroker__Host=amqp://texastaco-queue:5672
      - MessageBroker__Username=admin
      - MessageBroker__Password=1234
      - AuthCookies__Domain=localhost
      - DataProtectionSettings__CacheUri=authentication-cache
    ports:
      - "5002:8080"

  texastaco.products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ProductsDatabase__ConnectionString=server=products-db;user=root;password=root1234;database=products;
      - AuthCookies__Domain=localhost
      - DataProtectionSettings__CacheUri=authentication-cache
      - AwsS3BucketClientOptions__ApiKey=isbYkOeEE19PU1eYzdOjHxFa7t9YXxg2FWDewVK3
    ports:
      - "5003:8080"

  texastaco.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DataProtectionSettings__CacheUri=authentication-cache
      - AuthCookies__Domain=localhost
      - MessageBroker__Host=amqp://texastaco-queue:5672
      - MessageBroker__Username=admin
      - MessageBroker__Password=1234

    ports:
      - "5004:8080"

  authentication-db:
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=authentication
    ports:
      - 3306:3306
    volumes:
      - authentication_db_volume:/var/lib/mysql
  
  users-db:
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=users
    ports:
      - 3307:3306
    volumes:
      - users_db_volume:/var/lib/mysql

  products-db:
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=products
    ports:
      - 3308:3306
    volumes:
      - products_db_volume:/var/lib/mysql

  authentication-cache:
    ports: 
      - 6379:6379

  texastaco-mq:
    hostname: texastaco-queue
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - "5672:5672"
      - "15672:15672" 

