// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TexasTaco.Users.Core.Data.EF;

#nullable disable

namespace TexasTaco.Users.Core.Data.EF.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TexasTaco.Users.Core.Entities.AccountCreatedInbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("MessageProcessed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MessageReceived")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccountCreatedInbox");
                });
#pragma warning restore 612, 618
        }
    }
}
